### ISSUE TITLE
Cannot use R because of undefined symbol in readline

### ISSUE THREAD

**Issue by SylvainCorlay** [conda-forge/r-feedstock#2] opened 2017-06-13 14:42 UTC
```bash
miniconda3/lib/R/bin/exec/R: symbol lookup error: miniconda3/lib/R/bin/exec/../../lib/../../libreadline.so.6: undefined symbol: PC
```

**Comment by johanneskoester** [comment] 2017-06-13 16:06
Thanks! What is you channel setup?

**Comment by SylvainCorlay** [comment] 2017-06-13 16:09
Only default. forcibly enabling `conda-forge` with `conda install r -c conda-forge`.

**Comment by SylvainCorlay** [comment] 2017-06-13 16:10
The one from the `r` channel does not seem to have this issue.

**Comment by johanneskoester** [comment] 2017-06-13 16:17
Could it be that when you did that installation readline was already present, but coming from defaults? This would explain it, because the readline from conda-forge is likely configured a bit different. The recommendation is to either install everything from conda-forge or everything from defaults. The two are not binary compatible.

**Comment by SylvainCorlay** [comment] 2017-06-13 16:19
gotcha. There were some similar issues with gdal.

Some low-level packages are still missing in conda-forge (util-linux on linux and others) which makes not possible yet to have a pure conda-forge miniconda ...

**Comment by SylvainCorlay** [comment] 2017-06-13 16:20
I will try from a new clean miniconda.

**Comment by johanneskoester** [comment] 2017-06-13 16:22
Pure is not necessary. It is sufficient to have conda forge as highest priority channel.

**Comment by SylvainCorlay** [comment] 2017-06-13 17:09
The following CI build seems to show that even with conda-forge being at the higher priority, we have that issue:
https://travis-ci.org/SylvainCorlay/xtensor-r/jobs/242504699

The conda documentation says:

*The command conda config --add channels new_channel adds the new channel to the top of the channel list, making it the highest priority.*

cf https://conda.io/docs/channels.html

**Comment by johanneskoester** [comment] 2017-06-13 17:15
I see. @conda-forge/core, are you aware of this?

**Comment by isuruf** [comment] 2017-06-13 18:24
After adding the channel, you'll have to update everything. `conda update readline` should do it

**Comment by bgruening** [comment] 2017-06-13 20:58
@isuruf @jakirkham not sure if related to this issue but there is something fishy. You can reproduce this in the lastest condaforge/linux-anvil Docker image.

```
(root) [root@7a5e32daa30d /]# conda --version
conda 4.2.13
conda create -v -p /usr/local -c conda-forge r-yaml r-base  # -> readline 6.2-0 & r-base 3.3.2-5 
conda create -v -p /usr/local -c conda-forge r-yaml         # -> readline 7.0-0 & r-base 3.3.2-1
```
Please note that r-base was compiled with readline 6.2.* as seen here: https://github.com/conda-forge/r-base-feedstock/blob/master/recipe/meta.yaml#L40. So we should never ever get readline7 and I would also expect the same packages in both cases.

I also tested it with conda 4.3.21 and got the same results.

**Comment by bgruening** [comment] 2017-06-13 21:09
build-0 and build-1 of r-base are unpinned and should probably be tagged as damaged or removed.
However, this is probably also a conda bug in resolving the dependency tree.

**Comment by ocefpaf** [comment] 2017-06-13 21:11
> However, this is probably also a conda bug in resolving the dependency tree.

IMO when conda solver gets a lower build number when triggle o grok the pinned dependencies is a bug.
But since I gave up that discussion I will label them as broken to avoid headaches.

**Comment by bgruening** [comment] 2017-06-13 21:12
@ocefpaf thanks! Any issue where I can assist you in this discussion?

**Comment by ocefpaf** [comment] 2017-06-13 21:14
> @ocefpaf thanks! Any issue where I can assist you in this discussion?

We had many in conda-forge's early history. Not worth digging them up. I would open a new one if you want to revive that discussion.

PS: just to be sure you mean r-base build 0 and 1, right?

**Comment by bgruening** [comment] 2017-06-13 21:17
Yes, r-base. You fixed it in: https://github.com/conda-forge/r-base-feedstock/commit/eb951ec69358293b36330afc79627c2645fc92b9

@kalefranz do you have any idea about this bug?

**Comment by ocefpaf** [comment] 2017-06-14 15:03
> Yes, r-base. You fixed it in: https://github.com/conda-forge/r-base-feedstock/commit/eb951ec69358293b36330afc79627c2645fc92b9

Should be OK now. Let me know if you still see issues with build number >2

PS: continuum's policy with build number is non-intuitive and different from the packaging world. They `hotfix` the packages instead of bumping and using the latest one. That is fine, but what we consider a bug they consider a feature :smile:

**Comment by bgruening** [comment] 2017-06-14 15:41
mh, interesting! Thanks for fixing and the explanation!
@SylvainCorlay hope it is fixed for you as well. Please feel free to reopen if not.

**Closed as completed by bgruening** 2017-06-14 15:41 UTC

**Comment by jjhelmus** [comment] 2017-06-14 15:51
Hotfixing or removing packages is necessary because conda considers all build numbers when resolving dependencies.  If a package contains incorrect requirements simply releasing a new build will not solve the issue because this does not invalidate the older build(s).  

There have been discussions about changing this behavior so that only the latest build is considered but before this can be done some additions to conda and likely conda-build are needed.  

Consider the case where a package which depends on `jpeg` is needed with the requirements pinned to `jpeg8` and separately `jpeg9`.  Two packages are required and the solver should consider both when resolving dependencies.  The two packages would likely have the same version and dependencies (besides the jpeg pinning) and would likely differ either by build number or by using a different build string.  If they differ only in build number then restricting the solver to using only the latest build would cause issues. Changing the build string is a better option but the solver does not take this information into consideration.  Assigning meaning to the build string at this point seems to me a bad idea.

**Comment by johanneskoester** [comment] 2017-06-14 16:46
@jjhelmus, but if I am not mistaken, what you describe will be solved by conda build 3 where the build string is replaced by a hash, right?

**Comment by jjhelmus** [comment] 2017-06-14 17:17
@johanneskoester I don't think the hash in the build string added by conda build 3 really effect this issue.  The hash will change if the package's requirements change but conda still lacks a mechanism to communicate if this change is an update to correct invalid requirements or an entirely different build.

**Comment by johanneskoester** [comment] 2017-06-14 17:20
I was talking about your jpeg pinning story. This would get reflected in the hash, and therefore one would not necessarily need to update the build number. Hence, build number could be used for fixes only. However, I have not really thought this through.

**Comment by jjhelmus** [comment] 2017-06-14 17:39
I would be possible to have the two jpeg packages maintain the same build number.  The difference in the hash would differentiate the version of jpeg in the requirements (foo_py27habcdef_1.tar.bz2 and foo_py27h0123456_1.tar.bz2) although this can already be done by explicitly setting the build string in the recipe (foo_py27jpeg9_1.tar.bz2 vs foo_py26jpeg8_1.bz2).  In either case the solver would need to assign significance to the build string which is currently does not.

**Comment by johanneskoester** [comment] 2017-06-14 17:51
I don't think so. In both cases, it can say, when the build number is the same, I consider both packages for my solution and choose the one that fits. Without looking at the build string at all. And then, it can always consider only the latest build number. But I think this introduces other problems because you have to keep the build number synchronized. Maybe removing broken packages is just fine. It should be ok to advice people to not pin against build numbers in their environments.

**Comment by ocefpaf** [comment] 2017-06-14 17:53
> There have been discussions about changing this behavior so that only the latest build is considered but before this can be done some additions to conda and likely conda-build are needed.

@jjhelmus just to be clear I am not complaining! My mind set is biased to what happens in the linux world.
From the conda point of view conda-forge is broken when we assume that lower build number should not be considered.

I would welcome the change in the behavior, but if we (conda-forge) do our pinning properly and move unpinned software to the "broken" `label` everything works just fine too.

**Comment by jjhelmus** [comment] 2017-06-14 18:15
@johanneskoester You are right, with the hash as long as the build numbers of the two packages are synchronized the solver doesn't need to consider the build string.  Having to rebuild all variants to invalidate one may be burdensome for some packages but if the build number of the good packages can be patched even that might not be needed. I'll have to give it some though.

**Comment by SylvainCorlay** [comment] 2017-09-10 14:01
This sort of issue with `default` serving higher build numbers or version numbers makes me think that it could actually be very useful to create a conda-forge miniconda with conda constructor...

**Comment by jakirkham** [comment] 2017-09-10 16:18
Please see [this]( https://github.com/conda-forge/conda-forge-anvil ), @SylvainCorlay. Still needs a lot of work including figuring out the name to use.
